# -*- coding: utf-8 -*-
"""DS-Project.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x-gQGse6bzN1TeGgjVZlIuZ9bjYyvl0D
"""

import pandas as pd
import io
import matplotlib
from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

uploaded

sampleCSV = pd.read_csv(io.StringIO(uploaded['Country_Level_Info.csv'].decode('utf-8')))
sampleCSV